spring:
  application:
    name: Glim_Server

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cache:
    type: redis


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

jwt:
  secret: ENC(/jt4ypobScuVa5dMsAPoSAfVGs1L4AkVqjrooKxYM+u/TboQz4DOsxpiHNnWk8YmP8nN3YTQPIPG1D+fxLmG4GPJkyihZ/CvYOGaCiZGx5w=)
  access-token-validity-in-minutes: 15
  refresh-token-validity-in-days: 7

oci:
  namespace: ENC(l2xIgNKXGn7Guj4uQRD9sIkfWiBmgU/uFGSWFVYwMcsZYxu6OX4/01TRCcAVDZid)
  bucket: Glim_Image
  region: ap-chuncheon-1

aladin:
  base-url: https://www.aladin.co.kr
  ttb-key: ENC(Xgl/ntCpri/zEQiIzrjQXJpc6O8rnFtliXaLMeF1SAhE7pUTk7x22AdTk8X5OFqpEY4lud9QZcgs6atfEXpUng==)
  output: JS
  version: 20131101

pollination:
  base-url: https://gen.pollinations.ai/image
  key: ENC(GTYetLWNepVE2SNnS6YwbG6URRXFyjazKvfxMMA1YSGFQrVEJ/NcCw6hfB0n7kOeAMFhz280/brJPK8Mtv3xwwugag+YOGD0ubC6/Gi67Pg=)
  height: 1792
  width: 1024
  model: flux

gemini:
  key: ENC(X73K/8bny9ofMFRlFKFxshx2sB6dmvDu8+frSUVv3Ht/A8440BxiFntEU9XWPaJeyeV4wDYsAb6terPdKeL6sjnO3sWm0adNp2YFRzSSm/o=)
  model: gemini-3.5-flash
  base-url: https://generativelanguage.googleapis.com